package com.logistics.persistence.model;

import java.io.Serializable;
import java.util.Date;

public class Placard implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_placard.id
	 * @mbggenerated  Thu May 19 20:23:52 CST 2016
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_placard.title
	 * @mbggenerated  Thu May 19 20:23:52 CST 2016
	 */
	private String title;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_placard.content
	 * @mbggenerated  Thu May 19 20:23:52 CST 2016
	 */
	private String content;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_placard.create_time
	 * @mbggenerated  Thu May 19 20:23:52 CST 2016
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_placard
	 * @mbggenerated  Thu May 19 20:23:52 CST 2016
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_placard.id
	 * @return  the value of t_placard.id
	 * @mbggenerated  Thu May 19 20:23:52 CST 2016
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_placard.id
	 * @param id  the value for t_placard.id
	 * @mbggenerated  Thu May 19 20:23:52 CST 2016
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_placard.title
	 * @return  the value of t_placard.title
	 * @mbggenerated  Thu May 19 20:23:52 CST 2016
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_placard.title
	 * @param title  the value for t_placard.title
	 * @mbggenerated  Thu May 19 20:23:52 CST 2016
	 */
	public void setTitle(String title) {
		this.title = title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_placard.content
	 * @return  the value of t_placard.content
	 * @mbggenerated  Thu May 19 20:23:52 CST 2016
	 */
	public String getContent() {
		return content;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_placard.content
	 * @param content  the value for t_placard.content
	 * @mbggenerated  Thu May 19 20:23:52 CST 2016
	 */
	public void setContent(String content) {
		this.content = content;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_placard.create_time
	 * @return  the value of t_placard.create_time
	 * @mbggenerated  Thu May 19 20:23:52 CST 2016
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_placard.create_time
	 * @param createTime  the value for t_placard.create_time
	 * @mbggenerated  Thu May 19 20:23:52 CST 2016
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}
}