package com.logistics.persistence.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class UserExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_user
	 * @mbggenerated  Thu May 19 20:23:52 CST 2016
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_user
	 * @mbggenerated  Thu May 19 20:23:52 CST 2016
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_user
	 * @mbggenerated  Thu May 19 20:23:52 CST 2016
	 */
	protected List<Criteria> oredCriteria;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_user
	 * @mbggenerated  Thu May 19 20:23:52 CST 2016
	 */
	protected int limitStart;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_user
	 * @mbggenerated  Thu May 19 20:23:52 CST 2016
	 */
	protected int limitEnd;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_user
	 * @mbggenerated  Thu May 19 20:23:52 CST 2016
	 */
	protected String groupByClause;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user
	 * @mbggenerated  Thu May 19 20:23:52 CST 2016
	 */
	public UserExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user
	 * @mbggenerated  Thu May 19 20:23:52 CST 2016
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user
	 * @mbggenerated  Thu May 19 20:23:52 CST 2016
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user
	 * @mbggenerated  Thu May 19 20:23:52 CST 2016
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user
	 * @mbggenerated  Thu May 19 20:23:52 CST 2016
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user
	 * @mbggenerated  Thu May 19 20:23:52 CST 2016
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user
	 * @mbggenerated  Thu May 19 20:23:52 CST 2016
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user
	 * @mbggenerated  Thu May 19 20:23:52 CST 2016
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user
	 * @mbggenerated  Thu May 19 20:23:52 CST 2016
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user
	 * @mbggenerated  Thu May 19 20:23:52 CST 2016
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user
	 * @mbggenerated  Thu May 19 20:23:52 CST 2016
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user
	 * @mbggenerated  Thu May 19 20:23:52 CST 2016
	 */
	public void setLimitStart(int limitStart) {
		this.limitStart = limitStart;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user
	 * @mbggenerated  Thu May 19 20:23:52 CST 2016
	 */
	public int getLimitStart() {
		return limitStart;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user
	 * @mbggenerated  Thu May 19 20:23:52 CST 2016
	 */
	public void setLimitEnd(int limitEnd) {
		this.limitEnd = limitEnd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user
	 * @mbggenerated  Thu May 19 20:23:52 CST 2016
	 */
	public int getLimitEnd() {
		return limitEnd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user
	 * @mbggenerated  Thu May 19 20:23:52 CST 2016
	 */
	public void setGroupByClause(String groupByClause) {
		this.groupByClause = groupByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user
	 * @mbggenerated  Thu May 19 20:23:52 CST 2016
	 */
	public String getGroupByClause() {
		return groupByClause;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table t_user
	 * @mbggenerated  Thu May 19 20:23:52 CST 2016
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andUsrIdIsNull() {
			addCriterion("usr_id is null");
			return (Criteria) this;
		}

		public Criteria andUsrIdIsNotNull() {
			addCriterion("usr_id is not null");
			return (Criteria) this;
		}

		public Criteria andUsrIdEqualTo(Long value) {
			addCriterion("usr_id =", value, "usrId");
			return (Criteria) this;
		}

		public Criteria andUsrIdNotEqualTo(Long value) {
			addCriterion("usr_id <>", value, "usrId");
			return (Criteria) this;
		}

		public Criteria andUsrIdGreaterThan(Long value) {
			addCriterion("usr_id >", value, "usrId");
			return (Criteria) this;
		}

		public Criteria andUsrIdGreaterThanOrEqualTo(Long value) {
			addCriterion("usr_id >=", value, "usrId");
			return (Criteria) this;
		}

		public Criteria andUsrIdLessThan(Long value) {
			addCriterion("usr_id <", value, "usrId");
			return (Criteria) this;
		}

		public Criteria andUsrIdLessThanOrEqualTo(Long value) {
			addCriterion("usr_id <=", value, "usrId");
			return (Criteria) this;
		}

		public Criteria andUsrIdIn(List<Long> values) {
			addCriterion("usr_id in", values, "usrId");
			return (Criteria) this;
		}

		public Criteria andUsrIdNotIn(List<Long> values) {
			addCriterion("usr_id not in", values, "usrId");
			return (Criteria) this;
		}

		public Criteria andUsrIdBetween(Long value1, Long value2) {
			addCriterion("usr_id between", value1, value2, "usrId");
			return (Criteria) this;
		}

		public Criteria andUsrIdNotBetween(Long value1, Long value2) {
			addCriterion("usr_id not between", value1, value2, "usrId");
			return (Criteria) this;
		}

		public Criteria andUsrAccountIsNull() {
			addCriterion("usr_account is null");
			return (Criteria) this;
		}

		public Criteria andUsrAccountIsNotNull() {
			addCriterion("usr_account is not null");
			return (Criteria) this;
		}

		public Criteria andUsrAccountEqualTo(String value) {
			addCriterion("usr_account =", value, "usrAccount");
			return (Criteria) this;
		}

		public Criteria andUsrAccountNotEqualTo(String value) {
			addCriterion("usr_account <>", value, "usrAccount");
			return (Criteria) this;
		}

		public Criteria andUsrAccountGreaterThan(String value) {
			addCriterion("usr_account >", value, "usrAccount");
			return (Criteria) this;
		}

		public Criteria andUsrAccountGreaterThanOrEqualTo(String value) {
			addCriterion("usr_account >=", value, "usrAccount");
			return (Criteria) this;
		}

		public Criteria andUsrAccountLessThan(String value) {
			addCriterion("usr_account <", value, "usrAccount");
			return (Criteria) this;
		}

		public Criteria andUsrAccountLessThanOrEqualTo(String value) {
			addCriterion("usr_account <=", value, "usrAccount");
			return (Criteria) this;
		}

		public Criteria andUsrAccountLike(String value) {
			addCriterion("usr_account like", value, "usrAccount");
			return (Criteria) this;
		}

		public Criteria andUsrAccountNotLike(String value) {
			addCriterion("usr_account not like", value, "usrAccount");
			return (Criteria) this;
		}

		public Criteria andUsrAccountIn(List<String> values) {
			addCriterion("usr_account in", values, "usrAccount");
			return (Criteria) this;
		}

		public Criteria andUsrAccountNotIn(List<String> values) {
			addCriterion("usr_account not in", values, "usrAccount");
			return (Criteria) this;
		}

		public Criteria andUsrAccountBetween(String value1, String value2) {
			addCriterion("usr_account between", value1, value2, "usrAccount");
			return (Criteria) this;
		}

		public Criteria andUsrAccountNotBetween(String value1, String value2) {
			addCriterion("usr_account not between", value1, value2, "usrAccount");
			return (Criteria) this;
		}

		public Criteria andUsrMobileIsNull() {
			addCriterion("usr_mobile is null");
			return (Criteria) this;
		}

		public Criteria andUsrMobileIsNotNull() {
			addCriterion("usr_mobile is not null");
			return (Criteria) this;
		}

		public Criteria andUsrMobileEqualTo(String value) {
			addCriterion("usr_mobile =", value, "usrMobile");
			return (Criteria) this;
		}

		public Criteria andUsrMobileNotEqualTo(String value) {
			addCriterion("usr_mobile <>", value, "usrMobile");
			return (Criteria) this;
		}

		public Criteria andUsrMobileGreaterThan(String value) {
			addCriterion("usr_mobile >", value, "usrMobile");
			return (Criteria) this;
		}

		public Criteria andUsrMobileGreaterThanOrEqualTo(String value) {
			addCriterion("usr_mobile >=", value, "usrMobile");
			return (Criteria) this;
		}

		public Criteria andUsrMobileLessThan(String value) {
			addCriterion("usr_mobile <", value, "usrMobile");
			return (Criteria) this;
		}

		public Criteria andUsrMobileLessThanOrEqualTo(String value) {
			addCriterion("usr_mobile <=", value, "usrMobile");
			return (Criteria) this;
		}

		public Criteria andUsrMobileLike(String value) {
			addCriterion("usr_mobile like", value, "usrMobile");
			return (Criteria) this;
		}

		public Criteria andUsrMobileNotLike(String value) {
			addCriterion("usr_mobile not like", value, "usrMobile");
			return (Criteria) this;
		}

		public Criteria andUsrMobileIn(List<String> values) {
			addCriterion("usr_mobile in", values, "usrMobile");
			return (Criteria) this;
		}

		public Criteria andUsrMobileNotIn(List<String> values) {
			addCriterion("usr_mobile not in", values, "usrMobile");
			return (Criteria) this;
		}

		public Criteria andUsrMobileBetween(String value1, String value2) {
			addCriterion("usr_mobile between", value1, value2, "usrMobile");
			return (Criteria) this;
		}

		public Criteria andUsrMobileNotBetween(String value1, String value2) {
			addCriterion("usr_mobile not between", value1, value2, "usrMobile");
			return (Criteria) this;
		}

		public Criteria andUsrPasswordIsNull() {
			addCriterion("usr_password is null");
			return (Criteria) this;
		}

		public Criteria andUsrPasswordIsNotNull() {
			addCriterion("usr_password is not null");
			return (Criteria) this;
		}

		public Criteria andUsrPasswordEqualTo(String value) {
			addCriterion("usr_password =", value, "usrPassword");
			return (Criteria) this;
		}

		public Criteria andUsrPasswordNotEqualTo(String value) {
			addCriterion("usr_password <>", value, "usrPassword");
			return (Criteria) this;
		}

		public Criteria andUsrPasswordGreaterThan(String value) {
			addCriterion("usr_password >", value, "usrPassword");
			return (Criteria) this;
		}

		public Criteria andUsrPasswordGreaterThanOrEqualTo(String value) {
			addCriterion("usr_password >=", value, "usrPassword");
			return (Criteria) this;
		}

		public Criteria andUsrPasswordLessThan(String value) {
			addCriterion("usr_password <", value, "usrPassword");
			return (Criteria) this;
		}

		public Criteria andUsrPasswordLessThanOrEqualTo(String value) {
			addCriterion("usr_password <=", value, "usrPassword");
			return (Criteria) this;
		}

		public Criteria andUsrPasswordLike(String value) {
			addCriterion("usr_password like", value, "usrPassword");
			return (Criteria) this;
		}

		public Criteria andUsrPasswordNotLike(String value) {
			addCriterion("usr_password not like", value, "usrPassword");
			return (Criteria) this;
		}

		public Criteria andUsrPasswordIn(List<String> values) {
			addCriterion("usr_password in", values, "usrPassword");
			return (Criteria) this;
		}

		public Criteria andUsrPasswordNotIn(List<String> values) {
			addCriterion("usr_password not in", values, "usrPassword");
			return (Criteria) this;
		}

		public Criteria andUsrPasswordBetween(String value1, String value2) {
			addCriterion("usr_password between", value1, value2, "usrPassword");
			return (Criteria) this;
		}

		public Criteria andUsrPasswordNotBetween(String value1, String value2) {
			addCriterion("usr_password not between", value1, value2, "usrPassword");
			return (Criteria) this;
		}

		public Criteria andUsrNickNameIsNull() {
			addCriterion("usr_nick_name is null");
			return (Criteria) this;
		}

		public Criteria andUsrNickNameIsNotNull() {
			addCriterion("usr_nick_name is not null");
			return (Criteria) this;
		}

		public Criteria andUsrNickNameEqualTo(String value) {
			addCriterion("usr_nick_name =", value, "usrNickName");
			return (Criteria) this;
		}

		public Criteria andUsrNickNameNotEqualTo(String value) {
			addCriterion("usr_nick_name <>", value, "usrNickName");
			return (Criteria) this;
		}

		public Criteria andUsrNickNameGreaterThan(String value) {
			addCriterion("usr_nick_name >", value, "usrNickName");
			return (Criteria) this;
		}

		public Criteria andUsrNickNameGreaterThanOrEqualTo(String value) {
			addCriterion("usr_nick_name >=", value, "usrNickName");
			return (Criteria) this;
		}

		public Criteria andUsrNickNameLessThan(String value) {
			addCriterion("usr_nick_name <", value, "usrNickName");
			return (Criteria) this;
		}

		public Criteria andUsrNickNameLessThanOrEqualTo(String value) {
			addCriterion("usr_nick_name <=", value, "usrNickName");
			return (Criteria) this;
		}

		public Criteria andUsrNickNameLike(String value) {
			addCriterion("usr_nick_name like", value, "usrNickName");
			return (Criteria) this;
		}

		public Criteria andUsrNickNameNotLike(String value) {
			addCriterion("usr_nick_name not like", value, "usrNickName");
			return (Criteria) this;
		}

		public Criteria andUsrNickNameIn(List<String> values) {
			addCriterion("usr_nick_name in", values, "usrNickName");
			return (Criteria) this;
		}

		public Criteria andUsrNickNameNotIn(List<String> values) {
			addCriterion("usr_nick_name not in", values, "usrNickName");
			return (Criteria) this;
		}

		public Criteria andUsrNickNameBetween(String value1, String value2) {
			addCriterion("usr_nick_name between", value1, value2, "usrNickName");
			return (Criteria) this;
		}

		public Criteria andUsrNickNameNotBetween(String value1, String value2) {
			addCriterion("usr_nick_name not between", value1, value2, "usrNickName");
			return (Criteria) this;
		}

		public Criteria andGroupIdIsNull() {
			addCriterion("group_id is null");
			return (Criteria) this;
		}

		public Criteria andGroupIdIsNotNull() {
			addCriterion("group_id is not null");
			return (Criteria) this;
		}

		public Criteria andGroupIdEqualTo(Integer value) {
			addCriterion("group_id =", value, "groupId");
			return (Criteria) this;
		}

		public Criteria andGroupIdNotEqualTo(Integer value) {
			addCriterion("group_id <>", value, "groupId");
			return (Criteria) this;
		}

		public Criteria andGroupIdGreaterThan(Integer value) {
			addCriterion("group_id >", value, "groupId");
			return (Criteria) this;
		}

		public Criteria andGroupIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("group_id >=", value, "groupId");
			return (Criteria) this;
		}

		public Criteria andGroupIdLessThan(Integer value) {
			addCriterion("group_id <", value, "groupId");
			return (Criteria) this;
		}

		public Criteria andGroupIdLessThanOrEqualTo(Integer value) {
			addCriterion("group_id <=", value, "groupId");
			return (Criteria) this;
		}

		public Criteria andGroupIdIn(List<Integer> values) {
			addCriterion("group_id in", values, "groupId");
			return (Criteria) this;
		}

		public Criteria andGroupIdNotIn(List<Integer> values) {
			addCriterion("group_id not in", values, "groupId");
			return (Criteria) this;
		}

		public Criteria andGroupIdBetween(Integer value1, Integer value2) {
			addCriterion("group_id between", value1, value2, "groupId");
			return (Criteria) this;
		}

		public Criteria andGroupIdNotBetween(Integer value1, Integer value2) {
			addCriterion("group_id not between", value1, value2, "groupId");
			return (Criteria) this;
		}

		public Criteria andStatusIsNull() {
			addCriterion("status is null");
			return (Criteria) this;
		}

		public Criteria andStatusIsNotNull() {
			addCriterion("status is not null");
			return (Criteria) this;
		}

		public Criteria andStatusEqualTo(Integer value) {
			addCriterion("status =", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotEqualTo(Integer value) {
			addCriterion("status <>", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThan(Integer value) {
			addCriterion("status >", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThanOrEqualTo(Integer value) {
			addCriterion("status >=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThan(Integer value) {
			addCriterion("status <", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThanOrEqualTo(Integer value) {
			addCriterion("status <=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusIn(List<Integer> values) {
			addCriterion("status in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotIn(List<Integer> values) {
			addCriterion("status not in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusBetween(Integer value1, Integer value2) {
			addCriterion("status between", value1, value2, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotBetween(Integer value1, Integer value2) {
			addCriterion("status not between", value1, value2, "status");
			return (Criteria) this;
		}

		public Criteria andRegisterTimeIsNull() {
			addCriterion("register_time is null");
			return (Criteria) this;
		}

		public Criteria andRegisterTimeIsNotNull() {
			addCriterion("register_time is not null");
			return (Criteria) this;
		}

		public Criteria andRegisterTimeEqualTo(Date value) {
			addCriterion("register_time =", value, "registerTime");
			return (Criteria) this;
		}

		public Criteria andRegisterTimeNotEqualTo(Date value) {
			addCriterion("register_time <>", value, "registerTime");
			return (Criteria) this;
		}

		public Criteria andRegisterTimeGreaterThan(Date value) {
			addCriterion("register_time >", value, "registerTime");
			return (Criteria) this;
		}

		public Criteria andRegisterTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("register_time >=", value, "registerTime");
			return (Criteria) this;
		}

		public Criteria andRegisterTimeLessThan(Date value) {
			addCriterion("register_time <", value, "registerTime");
			return (Criteria) this;
		}

		public Criteria andRegisterTimeLessThanOrEqualTo(Date value) {
			addCriterion("register_time <=", value, "registerTime");
			return (Criteria) this;
		}

		public Criteria andRegisterTimeIn(List<Date> values) {
			addCriterion("register_time in", values, "registerTime");
			return (Criteria) this;
		}

		public Criteria andRegisterTimeNotIn(List<Date> values) {
			addCriterion("register_time not in", values, "registerTime");
			return (Criteria) this;
		}

		public Criteria andRegisterTimeBetween(Date value1, Date value2) {
			addCriterion("register_time between", value1, value2, "registerTime");
			return (Criteria) this;
		}

		public Criteria andRegisterTimeNotBetween(Date value1, Date value2) {
			addCriterion("register_time not between", value1, value2, "registerTime");
			return (Criteria) this;
		}

		public Criteria andRegisterIpIsNull() {
			addCriterion("register_ip is null");
			return (Criteria) this;
		}

		public Criteria andRegisterIpIsNotNull() {
			addCriterion("register_ip is not null");
			return (Criteria) this;
		}

		public Criteria andRegisterIpEqualTo(String value) {
			addCriterion("register_ip =", value, "registerIp");
			return (Criteria) this;
		}

		public Criteria andRegisterIpNotEqualTo(String value) {
			addCriterion("register_ip <>", value, "registerIp");
			return (Criteria) this;
		}

		public Criteria andRegisterIpGreaterThan(String value) {
			addCriterion("register_ip >", value, "registerIp");
			return (Criteria) this;
		}

		public Criteria andRegisterIpGreaterThanOrEqualTo(String value) {
			addCriterion("register_ip >=", value, "registerIp");
			return (Criteria) this;
		}

		public Criteria andRegisterIpLessThan(String value) {
			addCriterion("register_ip <", value, "registerIp");
			return (Criteria) this;
		}

		public Criteria andRegisterIpLessThanOrEqualTo(String value) {
			addCriterion("register_ip <=", value, "registerIp");
			return (Criteria) this;
		}

		public Criteria andRegisterIpLike(String value) {
			addCriterion("register_ip like", value, "registerIp");
			return (Criteria) this;
		}

		public Criteria andRegisterIpNotLike(String value) {
			addCriterion("register_ip not like", value, "registerIp");
			return (Criteria) this;
		}

		public Criteria andRegisterIpIn(List<String> values) {
			addCriterion("register_ip in", values, "registerIp");
			return (Criteria) this;
		}

		public Criteria andRegisterIpNotIn(List<String> values) {
			addCriterion("register_ip not in", values, "registerIp");
			return (Criteria) this;
		}

		public Criteria andRegisterIpBetween(String value1, String value2) {
			addCriterion("register_ip between", value1, value2, "registerIp");
			return (Criteria) this;
		}

		public Criteria andRegisterIpNotBetween(String value1, String value2) {
			addCriterion("register_ip not between", value1, value2, "registerIp");
			return (Criteria) this;
		}

		public Criteria andLoginIpIsNull() {
			addCriterion("login_ip is null");
			return (Criteria) this;
		}

		public Criteria andLoginIpIsNotNull() {
			addCriterion("login_ip is not null");
			return (Criteria) this;
		}

		public Criteria andLoginIpEqualTo(String value) {
			addCriterion("login_ip =", value, "loginIp");
			return (Criteria) this;
		}

		public Criteria andLoginIpNotEqualTo(String value) {
			addCriterion("login_ip <>", value, "loginIp");
			return (Criteria) this;
		}

		public Criteria andLoginIpGreaterThan(String value) {
			addCriterion("login_ip >", value, "loginIp");
			return (Criteria) this;
		}

		public Criteria andLoginIpGreaterThanOrEqualTo(String value) {
			addCriterion("login_ip >=", value, "loginIp");
			return (Criteria) this;
		}

		public Criteria andLoginIpLessThan(String value) {
			addCriterion("login_ip <", value, "loginIp");
			return (Criteria) this;
		}

		public Criteria andLoginIpLessThanOrEqualTo(String value) {
			addCriterion("login_ip <=", value, "loginIp");
			return (Criteria) this;
		}

		public Criteria andLoginIpLike(String value) {
			addCriterion("login_ip like", value, "loginIp");
			return (Criteria) this;
		}

		public Criteria andLoginIpNotLike(String value) {
			addCriterion("login_ip not like", value, "loginIp");
			return (Criteria) this;
		}

		public Criteria andLoginIpIn(List<String> values) {
			addCriterion("login_ip in", values, "loginIp");
			return (Criteria) this;
		}

		public Criteria andLoginIpNotIn(List<String> values) {
			addCriterion("login_ip not in", values, "loginIp");
			return (Criteria) this;
		}

		public Criteria andLoginIpBetween(String value1, String value2) {
			addCriterion("login_ip between", value1, value2, "loginIp");
			return (Criteria) this;
		}

		public Criteria andLoginIpNotBetween(String value1, String value2) {
			addCriterion("login_ip not between", value1, value2, "loginIp");
			return (Criteria) this;
		}

		public Criteria andRegDevKeyIsNull() {
			addCriterion("reg_dev_key is null");
			return (Criteria) this;
		}

		public Criteria andRegDevKeyIsNotNull() {
			addCriterion("reg_dev_key is not null");
			return (Criteria) this;
		}

		public Criteria andRegDevKeyEqualTo(String value) {
			addCriterion("reg_dev_key =", value, "regDevKey");
			return (Criteria) this;
		}

		public Criteria andRegDevKeyNotEqualTo(String value) {
			addCriterion("reg_dev_key <>", value, "regDevKey");
			return (Criteria) this;
		}

		public Criteria andRegDevKeyGreaterThan(String value) {
			addCriterion("reg_dev_key >", value, "regDevKey");
			return (Criteria) this;
		}

		public Criteria andRegDevKeyGreaterThanOrEqualTo(String value) {
			addCriterion("reg_dev_key >=", value, "regDevKey");
			return (Criteria) this;
		}

		public Criteria andRegDevKeyLessThan(String value) {
			addCriterion("reg_dev_key <", value, "regDevKey");
			return (Criteria) this;
		}

		public Criteria andRegDevKeyLessThanOrEqualTo(String value) {
			addCriterion("reg_dev_key <=", value, "regDevKey");
			return (Criteria) this;
		}

		public Criteria andRegDevKeyLike(String value) {
			addCriterion("reg_dev_key like", value, "regDevKey");
			return (Criteria) this;
		}

		public Criteria andRegDevKeyNotLike(String value) {
			addCriterion("reg_dev_key not like", value, "regDevKey");
			return (Criteria) this;
		}

		public Criteria andRegDevKeyIn(List<String> values) {
			addCriterion("reg_dev_key in", values, "regDevKey");
			return (Criteria) this;
		}

		public Criteria andRegDevKeyNotIn(List<String> values) {
			addCriterion("reg_dev_key not in", values, "regDevKey");
			return (Criteria) this;
		}

		public Criteria andRegDevKeyBetween(String value1, String value2) {
			addCriterion("reg_dev_key between", value1, value2, "regDevKey");
			return (Criteria) this;
		}

		public Criteria andRegDevKeyNotBetween(String value1, String value2) {
			addCriterion("reg_dev_key not between", value1, value2, "regDevKey");
			return (Criteria) this;
		}

		public Criteria andLoginDevKeyIsNull() {
			addCriterion("login_dev_key is null");
			return (Criteria) this;
		}

		public Criteria andLoginDevKeyIsNotNull() {
			addCriterion("login_dev_key is not null");
			return (Criteria) this;
		}

		public Criteria andLoginDevKeyEqualTo(String value) {
			addCriterion("login_dev_key =", value, "loginDevKey");
			return (Criteria) this;
		}

		public Criteria andLoginDevKeyNotEqualTo(String value) {
			addCriterion("login_dev_key <>", value, "loginDevKey");
			return (Criteria) this;
		}

		public Criteria andLoginDevKeyGreaterThan(String value) {
			addCriterion("login_dev_key >", value, "loginDevKey");
			return (Criteria) this;
		}

		public Criteria andLoginDevKeyGreaterThanOrEqualTo(String value) {
			addCriterion("login_dev_key >=", value, "loginDevKey");
			return (Criteria) this;
		}

		public Criteria andLoginDevKeyLessThan(String value) {
			addCriterion("login_dev_key <", value, "loginDevKey");
			return (Criteria) this;
		}

		public Criteria andLoginDevKeyLessThanOrEqualTo(String value) {
			addCriterion("login_dev_key <=", value, "loginDevKey");
			return (Criteria) this;
		}

		public Criteria andLoginDevKeyLike(String value) {
			addCriterion("login_dev_key like", value, "loginDevKey");
			return (Criteria) this;
		}

		public Criteria andLoginDevKeyNotLike(String value) {
			addCriterion("login_dev_key not like", value, "loginDevKey");
			return (Criteria) this;
		}

		public Criteria andLoginDevKeyIn(List<String> values) {
			addCriterion("login_dev_key in", values, "loginDevKey");
			return (Criteria) this;
		}

		public Criteria andLoginDevKeyNotIn(List<String> values) {
			addCriterion("login_dev_key not in", values, "loginDevKey");
			return (Criteria) this;
		}

		public Criteria andLoginDevKeyBetween(String value1, String value2) {
			addCriterion("login_dev_key between", value1, value2, "loginDevKey");
			return (Criteria) this;
		}

		public Criteria andLoginDevKeyNotBetween(String value1, String value2) {
			addCriterion("login_dev_key not between", value1, value2, "loginDevKey");
			return (Criteria) this;
		}

		public Criteria andLastLoginTimeIsNull() {
			addCriterion("last_login_time is null");
			return (Criteria) this;
		}

		public Criteria andLastLoginTimeIsNotNull() {
			addCriterion("last_login_time is not null");
			return (Criteria) this;
		}

		public Criteria andLastLoginTimeEqualTo(Date value) {
			addCriterion("last_login_time =", value, "lastLoginTime");
			return (Criteria) this;
		}

		public Criteria andLastLoginTimeNotEqualTo(Date value) {
			addCriterion("last_login_time <>", value, "lastLoginTime");
			return (Criteria) this;
		}

		public Criteria andLastLoginTimeGreaterThan(Date value) {
			addCriterion("last_login_time >", value, "lastLoginTime");
			return (Criteria) this;
		}

		public Criteria andLastLoginTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("last_login_time >=", value, "lastLoginTime");
			return (Criteria) this;
		}

		public Criteria andLastLoginTimeLessThan(Date value) {
			addCriterion("last_login_time <", value, "lastLoginTime");
			return (Criteria) this;
		}

		public Criteria andLastLoginTimeLessThanOrEqualTo(Date value) {
			addCriterion("last_login_time <=", value, "lastLoginTime");
			return (Criteria) this;
		}

		public Criteria andLastLoginTimeIn(List<Date> values) {
			addCriterion("last_login_time in", values, "lastLoginTime");
			return (Criteria) this;
		}

		public Criteria andLastLoginTimeNotIn(List<Date> values) {
			addCriterion("last_login_time not in", values, "lastLoginTime");
			return (Criteria) this;
		}

		public Criteria andLastLoginTimeBetween(Date value1, Date value2) {
			addCriterion("last_login_time between", value1, value2, "lastLoginTime");
			return (Criteria) this;
		}

		public Criteria andLastLoginTimeNotBetween(Date value1, Date value2) {
			addCriterion("last_login_time not between", value1, value2, "lastLoginTime");
			return (Criteria) this;
		}

		public Criteria andRegUserAgentIsNull() {
			addCriterion("reg_user_agent is null");
			return (Criteria) this;
		}

		public Criteria andRegUserAgentIsNotNull() {
			addCriterion("reg_user_agent is not null");
			return (Criteria) this;
		}

		public Criteria andRegUserAgentEqualTo(String value) {
			addCriterion("reg_user_agent =", value, "regUserAgent");
			return (Criteria) this;
		}

		public Criteria andRegUserAgentNotEqualTo(String value) {
			addCriterion("reg_user_agent <>", value, "regUserAgent");
			return (Criteria) this;
		}

		public Criteria andRegUserAgentGreaterThan(String value) {
			addCriterion("reg_user_agent >", value, "regUserAgent");
			return (Criteria) this;
		}

		public Criteria andRegUserAgentGreaterThanOrEqualTo(String value) {
			addCriterion("reg_user_agent >=", value, "regUserAgent");
			return (Criteria) this;
		}

		public Criteria andRegUserAgentLessThan(String value) {
			addCriterion("reg_user_agent <", value, "regUserAgent");
			return (Criteria) this;
		}

		public Criteria andRegUserAgentLessThanOrEqualTo(String value) {
			addCriterion("reg_user_agent <=", value, "regUserAgent");
			return (Criteria) this;
		}

		public Criteria andRegUserAgentLike(String value) {
			addCriterion("reg_user_agent like", value, "regUserAgent");
			return (Criteria) this;
		}

		public Criteria andRegUserAgentNotLike(String value) {
			addCriterion("reg_user_agent not like", value, "regUserAgent");
			return (Criteria) this;
		}

		public Criteria andRegUserAgentIn(List<String> values) {
			addCriterion("reg_user_agent in", values, "regUserAgent");
			return (Criteria) this;
		}

		public Criteria andRegUserAgentNotIn(List<String> values) {
			addCriterion("reg_user_agent not in", values, "regUserAgent");
			return (Criteria) this;
		}

		public Criteria andRegUserAgentBetween(String value1, String value2) {
			addCriterion("reg_user_agent between", value1, value2, "regUserAgent");
			return (Criteria) this;
		}

		public Criteria andRegUserAgentNotBetween(String value1, String value2) {
			addCriterion("reg_user_agent not between", value1, value2, "regUserAgent");
			return (Criteria) this;
		}

		public Criteria andLoginUserAgentIsNull() {
			addCriterion("login_user_agent is null");
			return (Criteria) this;
		}

		public Criteria andLoginUserAgentIsNotNull() {
			addCriterion("login_user_agent is not null");
			return (Criteria) this;
		}

		public Criteria andLoginUserAgentEqualTo(String value) {
			addCriterion("login_user_agent =", value, "loginUserAgent");
			return (Criteria) this;
		}

		public Criteria andLoginUserAgentNotEqualTo(String value) {
			addCriterion("login_user_agent <>", value, "loginUserAgent");
			return (Criteria) this;
		}

		public Criteria andLoginUserAgentGreaterThan(String value) {
			addCriterion("login_user_agent >", value, "loginUserAgent");
			return (Criteria) this;
		}

		public Criteria andLoginUserAgentGreaterThanOrEqualTo(String value) {
			addCriterion("login_user_agent >=", value, "loginUserAgent");
			return (Criteria) this;
		}

		public Criteria andLoginUserAgentLessThan(String value) {
			addCriterion("login_user_agent <", value, "loginUserAgent");
			return (Criteria) this;
		}

		public Criteria andLoginUserAgentLessThanOrEqualTo(String value) {
			addCriterion("login_user_agent <=", value, "loginUserAgent");
			return (Criteria) this;
		}

		public Criteria andLoginUserAgentLike(String value) {
			addCriterion("login_user_agent like", value, "loginUserAgent");
			return (Criteria) this;
		}

		public Criteria andLoginUserAgentNotLike(String value) {
			addCriterion("login_user_agent not like", value, "loginUserAgent");
			return (Criteria) this;
		}

		public Criteria andLoginUserAgentIn(List<String> values) {
			addCriterion("login_user_agent in", values, "loginUserAgent");
			return (Criteria) this;
		}

		public Criteria andLoginUserAgentNotIn(List<String> values) {
			addCriterion("login_user_agent not in", values, "loginUserAgent");
			return (Criteria) this;
		}

		public Criteria andLoginUserAgentBetween(String value1, String value2) {
			addCriterion("login_user_agent between", value1, value2, "loginUserAgent");
			return (Criteria) this;
		}

		public Criteria andLoginUserAgentNotBetween(String value1, String value2) {
			addCriterion("login_user_agent not between", value1, value2, "loginUserAgent");
			return (Criteria) this;
		}

		public Criteria andLoginTimesIsNull() {
			addCriterion("login_times is null");
			return (Criteria) this;
		}

		public Criteria andLoginTimesIsNotNull() {
			addCriterion("login_times is not null");
			return (Criteria) this;
		}

		public Criteria andLoginTimesEqualTo(Integer value) {
			addCriterion("login_times =", value, "loginTimes");
			return (Criteria) this;
		}

		public Criteria andLoginTimesNotEqualTo(Integer value) {
			addCriterion("login_times <>", value, "loginTimes");
			return (Criteria) this;
		}

		public Criteria andLoginTimesGreaterThan(Integer value) {
			addCriterion("login_times >", value, "loginTimes");
			return (Criteria) this;
		}

		public Criteria andLoginTimesGreaterThanOrEqualTo(Integer value) {
			addCriterion("login_times >=", value, "loginTimes");
			return (Criteria) this;
		}

		public Criteria andLoginTimesLessThan(Integer value) {
			addCriterion("login_times <", value, "loginTimes");
			return (Criteria) this;
		}

		public Criteria andLoginTimesLessThanOrEqualTo(Integer value) {
			addCriterion("login_times <=", value, "loginTimes");
			return (Criteria) this;
		}

		public Criteria andLoginTimesIn(List<Integer> values) {
			addCriterion("login_times in", values, "loginTimes");
			return (Criteria) this;
		}

		public Criteria andLoginTimesNotIn(List<Integer> values) {
			addCriterion("login_times not in", values, "loginTimes");
			return (Criteria) this;
		}

		public Criteria andLoginTimesBetween(Integer value1, Integer value2) {
			addCriterion("login_times between", value1, value2, "loginTimes");
			return (Criteria) this;
		}

		public Criteria andLoginTimesNotBetween(Integer value1, Integer value2) {
			addCriterion("login_times not between", value1, value2, "loginTimes");
			return (Criteria) this;
		}

		public Criteria andIsOnlineIsNull() {
			addCriterion("is_online is null");
			return (Criteria) this;
		}

		public Criteria andIsOnlineIsNotNull() {
			addCriterion("is_online is not null");
			return (Criteria) this;
		}

		public Criteria andIsOnlineEqualTo(Integer value) {
			addCriterion("is_online =", value, "isOnline");
			return (Criteria) this;
		}

		public Criteria andIsOnlineNotEqualTo(Integer value) {
			addCriterion("is_online <>", value, "isOnline");
			return (Criteria) this;
		}

		public Criteria andIsOnlineGreaterThan(Integer value) {
			addCriterion("is_online >", value, "isOnline");
			return (Criteria) this;
		}

		public Criteria andIsOnlineGreaterThanOrEqualTo(Integer value) {
			addCriterion("is_online >=", value, "isOnline");
			return (Criteria) this;
		}

		public Criteria andIsOnlineLessThan(Integer value) {
			addCriterion("is_online <", value, "isOnline");
			return (Criteria) this;
		}

		public Criteria andIsOnlineLessThanOrEqualTo(Integer value) {
			addCriterion("is_online <=", value, "isOnline");
			return (Criteria) this;
		}

		public Criteria andIsOnlineIn(List<Integer> values) {
			addCriterion("is_online in", values, "isOnline");
			return (Criteria) this;
		}

		public Criteria andIsOnlineNotIn(List<Integer> values) {
			addCriterion("is_online not in", values, "isOnline");
			return (Criteria) this;
		}

		public Criteria andIsOnlineBetween(Integer value1, Integer value2) {
			addCriterion("is_online between", value1, value2, "isOnline");
			return (Criteria) this;
		}

		public Criteria andIsOnlineNotBetween(Integer value1, Integer value2) {
			addCriterion("is_online not between", value1, value2, "isOnline");
			return (Criteria) this;
		}

		public Criteria andOnlineTimeIsNull() {
			addCriterion("online_time is null");
			return (Criteria) this;
		}

		public Criteria andOnlineTimeIsNotNull() {
			addCriterion("online_time is not null");
			return (Criteria) this;
		}

		public Criteria andOnlineTimeEqualTo(Date value) {
			addCriterion("online_time =", value, "onlineTime");
			return (Criteria) this;
		}

		public Criteria andOnlineTimeNotEqualTo(Date value) {
			addCriterion("online_time <>", value, "onlineTime");
			return (Criteria) this;
		}

		public Criteria andOnlineTimeGreaterThan(Date value) {
			addCriterion("online_time >", value, "onlineTime");
			return (Criteria) this;
		}

		public Criteria andOnlineTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("online_time >=", value, "onlineTime");
			return (Criteria) this;
		}

		public Criteria andOnlineTimeLessThan(Date value) {
			addCriterion("online_time <", value, "onlineTime");
			return (Criteria) this;
		}

		public Criteria andOnlineTimeLessThanOrEqualTo(Date value) {
			addCriterion("online_time <=", value, "onlineTime");
			return (Criteria) this;
		}

		public Criteria andOnlineTimeIn(List<Date> values) {
			addCriterion("online_time in", values, "onlineTime");
			return (Criteria) this;
		}

		public Criteria andOnlineTimeNotIn(List<Date> values) {
			addCriterion("online_time not in", values, "onlineTime");
			return (Criteria) this;
		}

		public Criteria andOnlineTimeBetween(Date value1, Date value2) {
			addCriterion("online_time between", value1, value2, "onlineTime");
			return (Criteria) this;
		}

		public Criteria andOnlineTimeNotBetween(Date value1, Date value2) {
			addCriterion("online_time not between", value1, value2, "onlineTime");
			return (Criteria) this;
		}

		public Criteria andSessionKeyIsNull() {
			addCriterion("session_key is null");
			return (Criteria) this;
		}

		public Criteria andSessionKeyIsNotNull() {
			addCriterion("session_key is not null");
			return (Criteria) this;
		}

		public Criteria andSessionKeyEqualTo(String value) {
			addCriterion("session_key =", value, "sessionKey");
			return (Criteria) this;
		}

		public Criteria andSessionKeyNotEqualTo(String value) {
			addCriterion("session_key <>", value, "sessionKey");
			return (Criteria) this;
		}

		public Criteria andSessionKeyGreaterThan(String value) {
			addCriterion("session_key >", value, "sessionKey");
			return (Criteria) this;
		}

		public Criteria andSessionKeyGreaterThanOrEqualTo(String value) {
			addCriterion("session_key >=", value, "sessionKey");
			return (Criteria) this;
		}

		public Criteria andSessionKeyLessThan(String value) {
			addCriterion("session_key <", value, "sessionKey");
			return (Criteria) this;
		}

		public Criteria andSessionKeyLessThanOrEqualTo(String value) {
			addCriterion("session_key <=", value, "sessionKey");
			return (Criteria) this;
		}

		public Criteria andSessionKeyLike(String value) {
			addCriterion("session_key like", value, "sessionKey");
			return (Criteria) this;
		}

		public Criteria andSessionKeyNotLike(String value) {
			addCriterion("session_key not like", value, "sessionKey");
			return (Criteria) this;
		}

		public Criteria andSessionKeyIn(List<String> values) {
			addCriterion("session_key in", values, "sessionKey");
			return (Criteria) this;
		}

		public Criteria andSessionKeyNotIn(List<String> values) {
			addCriterion("session_key not in", values, "sessionKey");
			return (Criteria) this;
		}

		public Criteria andSessionKeyBetween(String value1, String value2) {
			addCriterion("session_key between", value1, value2, "sessionKey");
			return (Criteria) this;
		}

		public Criteria andSessionKeyNotBetween(String value1, String value2) {
			addCriterion("session_key not between", value1, value2, "sessionKey");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table t_user
	 * @mbggenerated  Thu May 19 20:23:52 CST 2016
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_user
     *
     * @mbggenerated do_not_delete_during_merge Sun May 15 16:08:34 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}