package com.logistics.persistence.model;

import java.io.Serializable;
import java.util.Date;

public class User implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_user.usr_id
	 * @mbggenerated  Thu May 19 20:23:52 CST 2016
	 */
	private Long usrId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_user.usr_account
	 * @mbggenerated  Thu May 19 20:23:52 CST 2016
	 */
	private String usrAccount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_user.usr_mobile
	 * @mbggenerated  Thu May 19 20:23:52 CST 2016
	 */
	private String usrMobile;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_user.usr_password
	 * @mbggenerated  Thu May 19 20:23:52 CST 2016
	 */
	private String usrPassword;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_user.usr_nick_name
	 * @mbggenerated  Thu May 19 20:23:52 CST 2016
	 */
	private String usrNickName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_user.group_id
	 * @mbggenerated  Thu May 19 20:23:52 CST 2016
	 */
	private Integer groupId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_user.status
	 * @mbggenerated  Thu May 19 20:23:52 CST 2016
	 */
	private Integer status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_user.register_time
	 * @mbggenerated  Thu May 19 20:23:52 CST 2016
	 */
	private Date registerTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_user.register_ip
	 * @mbggenerated  Thu May 19 20:23:52 CST 2016
	 */
	private String registerIp;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_user.login_ip
	 * @mbggenerated  Thu May 19 20:23:52 CST 2016
	 */
	private String loginIp;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_user.reg_dev_key
	 * @mbggenerated  Thu May 19 20:23:52 CST 2016
	 */
	private String regDevKey;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_user.login_dev_key
	 * @mbggenerated  Thu May 19 20:23:52 CST 2016
	 */
	private String loginDevKey;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_user.last_login_time
	 * @mbggenerated  Thu May 19 20:23:52 CST 2016
	 */
	private Date lastLoginTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_user.reg_user_agent
	 * @mbggenerated  Thu May 19 20:23:52 CST 2016
	 */
	private String regUserAgent;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_user.login_user_agent
	 * @mbggenerated  Thu May 19 20:23:52 CST 2016
	 */
	private String loginUserAgent;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_user.login_times
	 * @mbggenerated  Thu May 19 20:23:52 CST 2016
	 */
	private Integer loginTimes;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_user.is_online
	 * @mbggenerated  Thu May 19 20:23:52 CST 2016
	 */
	private Integer isOnline;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_user.online_time
	 * @mbggenerated  Thu May 19 20:23:52 CST 2016
	 */
	private Date onlineTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_user.session_key
	 * @mbggenerated  Thu May 19 20:23:52 CST 2016
	 */
	private String sessionKey;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_user
	 * @mbggenerated  Thu May 19 20:23:52 CST 2016
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user.usr_id
	 * @return  the value of t_user.usr_id
	 * @mbggenerated  Thu May 19 20:23:52 CST 2016
	 */
	public Long getUsrId() {
		return usrId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user.usr_id
	 * @param usrId  the value for t_user.usr_id
	 * @mbggenerated  Thu May 19 20:23:52 CST 2016
	 */
	public void setUsrId(Long usrId) {
		this.usrId = usrId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user.usr_account
	 * @return  the value of t_user.usr_account
	 * @mbggenerated  Thu May 19 20:23:52 CST 2016
	 */
	public String getUsrAccount() {
		return usrAccount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user.usr_account
	 * @param usrAccount  the value for t_user.usr_account
	 * @mbggenerated  Thu May 19 20:23:52 CST 2016
	 */
	public void setUsrAccount(String usrAccount) {
		this.usrAccount = usrAccount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user.usr_mobile
	 * @return  the value of t_user.usr_mobile
	 * @mbggenerated  Thu May 19 20:23:52 CST 2016
	 */
	public String getUsrMobile() {
		return usrMobile;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user.usr_mobile
	 * @param usrMobile  the value for t_user.usr_mobile
	 * @mbggenerated  Thu May 19 20:23:52 CST 2016
	 */
	public void setUsrMobile(String usrMobile) {
		this.usrMobile = usrMobile;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user.usr_password
	 * @return  the value of t_user.usr_password
	 * @mbggenerated  Thu May 19 20:23:52 CST 2016
	 */
	public String getUsrPassword() {
		return usrPassword;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user.usr_password
	 * @param usrPassword  the value for t_user.usr_password
	 * @mbggenerated  Thu May 19 20:23:52 CST 2016
	 */
	public void setUsrPassword(String usrPassword) {
		this.usrPassword = usrPassword;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user.usr_nick_name
	 * @return  the value of t_user.usr_nick_name
	 * @mbggenerated  Thu May 19 20:23:52 CST 2016
	 */
	public String getUsrNickName() {
		return usrNickName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user.usr_nick_name
	 * @param usrNickName  the value for t_user.usr_nick_name
	 * @mbggenerated  Thu May 19 20:23:52 CST 2016
	 */
	public void setUsrNickName(String usrNickName) {
		this.usrNickName = usrNickName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user.group_id
	 * @return  the value of t_user.group_id
	 * @mbggenerated  Thu May 19 20:23:52 CST 2016
	 */
	public Integer getGroupId() {
		return groupId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user.group_id
	 * @param groupId  the value for t_user.group_id
	 * @mbggenerated  Thu May 19 20:23:52 CST 2016
	 */
	public void setGroupId(Integer groupId) {
		this.groupId = groupId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user.status
	 * @return  the value of t_user.status
	 * @mbggenerated  Thu May 19 20:23:52 CST 2016
	 */
	public Integer getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user.status
	 * @param status  the value for t_user.status
	 * @mbggenerated  Thu May 19 20:23:52 CST 2016
	 */
	public void setStatus(Integer status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user.register_time
	 * @return  the value of t_user.register_time
	 * @mbggenerated  Thu May 19 20:23:52 CST 2016
	 */
	public Date getRegisterTime() {
		return registerTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user.register_time
	 * @param registerTime  the value for t_user.register_time
	 * @mbggenerated  Thu May 19 20:23:52 CST 2016
	 */
	public void setRegisterTime(Date registerTime) {
		this.registerTime = registerTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user.register_ip
	 * @return  the value of t_user.register_ip
	 * @mbggenerated  Thu May 19 20:23:52 CST 2016
	 */
	public String getRegisterIp() {
		return registerIp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user.register_ip
	 * @param registerIp  the value for t_user.register_ip
	 * @mbggenerated  Thu May 19 20:23:52 CST 2016
	 */
	public void setRegisterIp(String registerIp) {
		this.registerIp = registerIp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user.login_ip
	 * @return  the value of t_user.login_ip
	 * @mbggenerated  Thu May 19 20:23:52 CST 2016
	 */
	public String getLoginIp() {
		return loginIp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user.login_ip
	 * @param loginIp  the value for t_user.login_ip
	 * @mbggenerated  Thu May 19 20:23:52 CST 2016
	 */
	public void setLoginIp(String loginIp) {
		this.loginIp = loginIp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user.reg_dev_key
	 * @return  the value of t_user.reg_dev_key
	 * @mbggenerated  Thu May 19 20:23:52 CST 2016
	 */
	public String getRegDevKey() {
		return regDevKey;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user.reg_dev_key
	 * @param regDevKey  the value for t_user.reg_dev_key
	 * @mbggenerated  Thu May 19 20:23:52 CST 2016
	 */
	public void setRegDevKey(String regDevKey) {
		this.regDevKey = regDevKey;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user.login_dev_key
	 * @return  the value of t_user.login_dev_key
	 * @mbggenerated  Thu May 19 20:23:52 CST 2016
	 */
	public String getLoginDevKey() {
		return loginDevKey;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user.login_dev_key
	 * @param loginDevKey  the value for t_user.login_dev_key
	 * @mbggenerated  Thu May 19 20:23:52 CST 2016
	 */
	public void setLoginDevKey(String loginDevKey) {
		this.loginDevKey = loginDevKey;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user.last_login_time
	 * @return  the value of t_user.last_login_time
	 * @mbggenerated  Thu May 19 20:23:52 CST 2016
	 */
	public Date getLastLoginTime() {
		return lastLoginTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user.last_login_time
	 * @param lastLoginTime  the value for t_user.last_login_time
	 * @mbggenerated  Thu May 19 20:23:52 CST 2016
	 */
	public void setLastLoginTime(Date lastLoginTime) {
		this.lastLoginTime = lastLoginTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user.reg_user_agent
	 * @return  the value of t_user.reg_user_agent
	 * @mbggenerated  Thu May 19 20:23:52 CST 2016
	 */
	public String getRegUserAgent() {
		return regUserAgent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user.reg_user_agent
	 * @param regUserAgent  the value for t_user.reg_user_agent
	 * @mbggenerated  Thu May 19 20:23:52 CST 2016
	 */
	public void setRegUserAgent(String regUserAgent) {
		this.regUserAgent = regUserAgent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user.login_user_agent
	 * @return  the value of t_user.login_user_agent
	 * @mbggenerated  Thu May 19 20:23:52 CST 2016
	 */
	public String getLoginUserAgent() {
		return loginUserAgent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user.login_user_agent
	 * @param loginUserAgent  the value for t_user.login_user_agent
	 * @mbggenerated  Thu May 19 20:23:52 CST 2016
	 */
	public void setLoginUserAgent(String loginUserAgent) {
		this.loginUserAgent = loginUserAgent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user.login_times
	 * @return  the value of t_user.login_times
	 * @mbggenerated  Thu May 19 20:23:52 CST 2016
	 */
	public Integer getLoginTimes() {
		return loginTimes;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user.login_times
	 * @param loginTimes  the value for t_user.login_times
	 * @mbggenerated  Thu May 19 20:23:52 CST 2016
	 */
	public void setLoginTimes(Integer loginTimes) {
		this.loginTimes = loginTimes;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user.is_online
	 * @return  the value of t_user.is_online
	 * @mbggenerated  Thu May 19 20:23:52 CST 2016
	 */
	public Integer getIsOnline() {
		return isOnline;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user.is_online
	 * @param isOnline  the value for t_user.is_online
	 * @mbggenerated  Thu May 19 20:23:52 CST 2016
	 */
	public void setIsOnline(Integer isOnline) {
		this.isOnline = isOnline;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user.online_time
	 * @return  the value of t_user.online_time
	 * @mbggenerated  Thu May 19 20:23:52 CST 2016
	 */
	public Date getOnlineTime() {
		return onlineTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user.online_time
	 * @param onlineTime  the value for t_user.online_time
	 * @mbggenerated  Thu May 19 20:23:52 CST 2016
	 */
	public void setOnlineTime(Date onlineTime) {
		this.onlineTime = onlineTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user.session_key
	 * @return  the value of t_user.session_key
	 * @mbggenerated  Thu May 19 20:23:52 CST 2016
	 */
	public String getSessionKey() {
		return sessionKey;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user.session_key
	 * @param sessionKey  the value for t_user.session_key
	 * @mbggenerated  Thu May 19 20:23:52 CST 2016
	 */
	public void setSessionKey(String sessionKey) {
		this.sessionKey = sessionKey;
	}
}